name: Release

permissions:
  contents: write

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - run: go version

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/ping-watcher-linux_x86_64 ./cmd
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o dist/ping-watcher-linux_arm64 ./cmd
          CGO_ENABLED=0 GOOS=linux GOARCH=arm   go build -o dist/ping-watcher-linux_arm ./cmd
          GOOS=windows GOARCH=amd64 go build -o dist/ping-watcher-windows_x86_64.exe ./cmd

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*
